name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Server Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: false
        tags: server:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build Web Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./web
        push: false
        tags: web:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Exemplo de como você faria deploy no Vercel via CLI se preferisse o GHA no lugar do push automático
    # - name: Deploy to Vercel (Optional)
    #   run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
